apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: catalog
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: grpc
          env:
            - name: DATABASE_URL
              value: "http://catalog-db-service:9200"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: grpc
  selector:
    app: catalog-service
  type: ClusterIP
